### ISSUE TITLE
با عرض سلام در سمپل ارائه شده نام داور ها و نماینده تحصیلات تکمیلی را که در که در فایل data وارد می کنم در خروجی چاپ نمیشن

### ISSUE THREAD

**Issue by maesomi** [alishakiba/vruthesis#1]

**Comment by alishakiba** [comment]
با سلام
صفحات مربوط به تصویب‌نامه‌ی پایان‌نامه را از تحصیلات تکمیلی دریافت کرده؛ آن‌ها را اسکن نموده و نام آن‌ها را به شرح زیر تغییر دهید:

- تصویب‌نامه‌ی فارسی: gradefa.pdf
- تصویب‌نامه‌ی انگلیسی: gradeen.pdf

سپس این فایل‌ها را با نمونه‌های هم‌نام در پوشه‌ی اصلی، جایگزین کنید. لطفا مد نظر داشته باشید که این فرم‌ها پس از دفاع از پایان‌نامه در اختیار شما قرار می‌گیرند.

این فایل‌ها به صورت پیش‌فرض در آدرس‌های https://github.com/alishakiba/vruthesis/blob/master/gradefa.pdf و https://github.com/alishakiba/vruthesis/blob/master/gradeen.pdf قرار دارند.

موفق باشید
