### ISSUE TITLE
داشتن خطا در اجرای اولیه

### ISSUE THREAD

**Issue by MakiAbadi** [alishakiba/vruthesis#2]
با سلام و وقت بخیر با توجه به راهنمای تصویری برای اجرای فایل زمان اجرای دستورات مربوط به فایل HowToBuild در cmd با این خطا مواجه شدم
![error](https://user-images.githubusercontent.com/39724695/40646349-1dd8f3d0-633e-11e8-91b4-71d02b147d98.JPG)

**Comment by alishakiba** [comment]
با سلام
دستورات صحیح به صورت زیر هستند. شما چند خط دستور را در یک خط نوشته اید:

`xelatex -synctex=-1 thesis.tex`
`bibtex8 -W -c cp1256fa thesis`
`xindy -L persian-variant1 -C utf8 -I xindy -M thesis.xdy -t thesis.glg -o thesis.gls thesis.glo`
`xindy -L persian-variant1 -C utf8 -I xindy -M thesis.xdy -t thesis.blg -o thesis.bls thesis.blo`
`xindy -L english -C utf8 -I xindy -M thesis.xdy -t thesis.alg -o thesis.acr thesis.acn`
`xelatex -synctex=-1 thesis.tex`
`xelatex -synctex=-1 thesis.tex`
