### ISSUE TITLE
افزودن فاصله بین خطوط الگوریتم

### ISSUE THREAD

**Issue by MakiAbadi** [alishakiba/vruthesis#3]
با سلام و وقت بخیر چگونه می‌توان فاصله بین خطوط الگوریتم را زیاد کرد؟
\begin{algorithm}[H]
\caption{ تقریب بیرونی بنسون } \label{algo}
\begin{algorithmic}[1]
		\State اگر برای هر $y\in vert(S^k)$ داشته باشیم $y\in \mathcal{Y}^\circ$ آن‌گاه $\mathcal{Y}^\circ = S^k$ و توقف کنید. در غیر این صورت یک $y^k \in vert(S^k)$ انتخاب کنید به طوری که $y^k \notin \mathcal{Y}^\circ$. 
		\State مقدار یکتا  $\lambda _k \in (0,1)$  را پیدا کنید به طوری که $\lambda_k y^k +(1-\lambda_k) \bar{p}$ متعلق به مرز $\mathcal{Y}^\circ$ باشد و قرار دهید $w^k = \lambda _k y^k +(1-\lambda_k) \bar{p}$. 
		\State قرار دهید $S^{k+1} =S^k \cap \{ y\in \mathbb{R}^p ~|~\langle u^k, y\rangle \geqslant \langle b, v^k\rangle\}$ که $((u^k)^t, (v^k)^t)$ جواب بهینه دوگان برنامه‌ریزی خطی $(Q_w)$ با $w=w^k$ است. 
		\State با استفاده از $vert(S^k)$ و تعریف $S^{k+1}$ داده شده در گام $3$ ، $vert(S^{k+1})$ را تعیین کنید. قرار دهید $k=k+1$ و به گام $1$ بروید. 
		%\Ensure
\end{algorithmic}
\end{algorithm} 

![algorithm](https://user-images.githubusercontent.com/39724695/42123867-56d9e9f2-7c6e-11e8-9696-824dda99413d.JPG)

**Comment by alishakiba** [comment]
با سلام
طبق آنچه که در [https://tex.stackexchange.com/questions/74849/increase-spacing-in-an-algorithm](اینجا) آمده است؛ لازم است تا ابتدا در فایل `thesis.tex` قبل از خط شامل دستور
`\usepackage[extrafootnotefeatures]{xepersian}`
دستورات زیر را اضافه نمایید. 
` \usepackage{setspace}`
`\let\Algorithm\algorithm`
`\renewcommand\algorithm[1][]{\Algorithm[#1]\setstretch{1.4}}`
همچنین مقدار ۱.۴ را به مقدار مورد نیاز خود تغییر دهید.

**Comment by alishakiba** [comment]
با توجه به عدم دریافت تایید صحت پاسخ از سمت شما، این سوال بسته می شود. در صورت نیاز، می توانید آن را مجددا باز نمایید.
