### ISSUE TITLE
نمایش ورودی و خروجی در الگوریتم

### ISSUE THREAD

**Issue by MakiAbadi** [alishakiba/vruthesis#4]
سلام و وقت بخیر چگونه می‌توان ورودی و خروجی را در الگوریتم وارد کرد؟
\begin{algorithm}[H]
\caption{ تقریب بیرونی بنسون } \label{algo}
\begin{algorithmic}[1]
		%\Require
%		\begin{itemize}
%		\item[ ]نقطه $\bar{p}\in int(\mathcal{Y}^\circ)$ را در نظر بگیرید و سادک $p$-بعدی $S^0=S$ را که  $\mathcal{Y}^\circ \subseteq S$  با توجه به توضیحات قضیه \ref{t:2.2} و \ref{t:2.3} بسازید. مجموعه رئوس $vert(S^0)$ و نمایش $S^0=S$ بیان شده در قضیه \ref{t:2.2} را ساخته و قرار دهید $k=0$. 
%		\end{itemize}
		\State اگر برای هر $y\in vert(S^k)$ داشته باشیم $y\in \mathcal{Y}^\circ$ آن‌گاه $\mathcal{Y}^\circ = S^k$ و توقف کنید. در غیر این صورت یک $y^k \in vert(S^k)$ انتخاب کنید به طوری که $y^k \notin \mathcal{Y}^\circ$. 
		\State مقدار یکتا  $\lambda _k \in (0,1)$  را پیدا کنید به طوری که $\lambda_k y^k +(1-\lambda_k) \bar{p}$ متعلق به مرز $\mathcal{Y}^\circ$ باشد و قرار دهید $w^k = \lambda _k y^k +(1-\lambda_k) \bar{p}$. 
		\State قرار دهید $S^{k+1} =S^k \cap \{ y\in \mathbb{R}^p ~|~\langle u^k, y\rangle \geqslant \langle b, v^k\rangle\}$ که $((u^k)^t, (v^k)^t)$ جواب بهینه دوگان برنامه‌ریزی خطی $(Q_w)$ با $w=w^k$ است. 
		\State با استفاده از $vert(S^k)$ و تعریف $S^{k+1}$ داده شده در گام $3$ ، $vert(S^{k+1})$ را تعیین کنید. قرار دهید $k=k+1$ و به گام $1$ بروید. 
		%\Ensure
\end{algorithmic}
\end{algorithm}

**Comment by alishakiba** [comment]
با  سلام
طبق آنچه که در [https://tex.stackexchange.com/a/98680/46759](اینجا) آمده است؛ شما می توانید از دستور زیر استفاده نمایید:
`\statex \textbf{ورودی}: ورودی ۱؛ ورودی ۲؛ ورودی ۳ و الی آخر`

**Comment by alishakiba** [comment]
با توجه به عدم دریافت تایید صحت پاسخ از سمت شما، این سوال بسته می شود. در صورت نیاز، می توانید آن را مجددا باز نمایید.
