### ISSUE TITLE
رفع مشکل خط تیره در رفرنسهایی که پشت سرهم هستند. خط تراز و فونت توضیحات زیر شکلها

### ISSUE THREAD

**Issue by davodisvand** [alishakiba/vruthesis#5]
سلام دکتر
بجای خط تیره در رفرنسهایی که پشت سرهم هستند مربع می‌زند.

باتشکر
داود ایسوند
![untitled](https://user-images.githubusercontent.com/35893012/43700905-93ccfb0c-9969-11e8-9aaa-10ea293f3575.jpg)
![untitled2](https://user-images.githubusercontent.com/35893012/43700989-e54fcbb2-9969-11e8-9512-4f9ed14bb2c3.jpg)

**Comment by alishakiba** [comment]
با سلام
لطفا فایل های 

vruthesis.cls

و 

settings.tex

را به روز رسانی نمایید.
ایراد مربوط به قلم 
B Nazanin
است که با بازتعریف خط تیره مشکل حل شده است.
موفق باشید.

**Comment by davodisvand** [comment]
سلام دکتر  و متشکرم ولی الان صفه اخر مشخصات پایان نامه مشکل دارد و آرم دانشگاه وسط نیست.
![untitled](https://user-images.githubusercontent.com/35893012/44146465-e53288e4-a0a4-11e8-91de-faa15cddf716.jpg)

**Comment by alishakiba** [comment]
با سلام
این موارد در به روزرسانی جدید اعمال شده اند.
