### ISSUE TITLE
مشکل کوچک بودن عنوان فصلها

### ISSUE THREAD

**Issue by davodisvand** [alishakiba/vruthesis#6]
با سلام و خسته نباشید.
عنوان فصلها در نسخه جدید خیلی کوچک شده به طوری که صفحه اول هر فصل که بایستی از صفحات دیگر متمایز باشد متمایز نیست. بطوری که شروع فصلها را نمیتوان با ورق زدن معمولی پیدا و مشخص کرد. من عنوان فصل اول در نسخه قدیمی و جدید را برای نمونه برای شما ارسال میکنم.
پیشاپیش از تلاشهای شما متشکریم.
نسخه قدیمی
![default](https://user-images.githubusercontent.com/35893012/44189709-350c3380-a139-11e8-8e4c-082b92b9160e.png)

نسخه جدید 
![default](https://user-images.githubusercontent.com/35893012/44189702-2de52580-a139-11e8-8373-62a43e2270a7.png)

**Comment by alishakiba** [comment]
با سلام
این موارد در به روزرسانی جدید اعمال شده اند.
