### ISSUE TITLE
مشکل بالا آمدن دیکشنری

### ISSUE THREAD

**Issue by mkolahdouz** [alishakiba/vruthesis#8]
سلام و خسته نباشید... من فایل
gloss.tex
رو کامل کردم و بعدش کنار تمام واژگانی که میخواستم ترجمشون در دیکشنری بیاد از دستور
\gls{file}
استفاده کردم، منتهی با اینکه تمام این لغات به رنگ آبی در پایان‌نامه ظاهر میشوند ولی در دیکشنری آخر پایان‌نامه هیچ لغتی دیده نمیشود... ممنون میشم کمکم کنید

**Comment by alishakiba** [comment]
با سلام
مربوط به عدم اجرای صحیح دستورات است
فایل 
GuideToUse.pdf
را ببینید.
